name = "NasPanoptiPack"
author = "naspen"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37f0f19e89a35f1d174829d7de141e834475f72d468282591b78218c9f910881"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
