name = "NasPanoptiWatcher"
author = "naspen"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c3388f5c031cb8db5eb9a804c5439400ee17fd1bdb5c23c997cc5c9a67e849f"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
